### ISSUE TITLE
Cache with loader returns null after ttl

### ISSUE THREAD

**Issue by bjanczak** [ehcache/ehcache3#1909] opened 2017-03-09 19:56 UTC
EHCache version 3.3.0

When multi tiered cache configured with loader and ttl, it returns null for the first get after ttl expires.

I include tests below:
- testNPE() - exposes a flaw in ehcache 3.3.0,
- testNoNPE() - shows how to live with that until fixed.

```java
package com.softwareplant.util.cacheint.multitenant;

import com.google.common.collect.Sets;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import org.ehcache.Cache;
import org.ehcache.CacheManager;
import org.ehcache.config.CacheConfiguration;
import org.ehcache.config.builders.CacheConfigurationBuilder;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.ehcache.config.builders.PooledExecutionServiceConfigurationBuilder;
import org.ehcache.config.builders.ResourcePoolsBuilder;
import org.ehcache.config.units.EntryUnit;
import org.ehcache.config.units.MemoryUnit;
import org.ehcache.expiry.Duration;
import org.ehcache.expiry.Expirations;
import org.ehcache.spi.loaderwriter.BulkCacheLoadingException;
import org.ehcache.spi.loaderwriter.BulkCacheWritingException;
import org.ehcache.spi.loaderwriter.CacheLoaderWriter;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

public class EhCache3BugTests {

	private CacheManager cacheManager;

	@Test
	@Ignore
	public void testNPE() {
		initCacheManager();
		Set<Integer> set = Sets.newHashSet();

		createCache(0, set);
		int i = 0;
		while (true) {
			Cache<Integer, String> c = cacheManager.getCache("XXX" + 0, Integer.class, String.class);
			Assert.assertNotNull(c);
			String s = c.get(100);
			Assert.assertNotNull("Iteracja " + i++, s);
		}
	}

	@Test
	@Ignore
	public void testNoNPE() {
		initCacheManager();
		Set<Integer> set = Sets.newHashSet();

		createCache(0, set);
		int i = 0;
		while (true) {
			Cache<Integer, String> c = cacheManager.getCache("XXX" + 0, Integer.class, String.class);
			Assert.assertNotNull(c);
			String s = c.get(100);
			if (s == null) {
				s = c.get(100);
			}
			Assert.assertNotNull("Iteracja " + i++, s);
		}
	}

	private void createCache(int i, Set<Integer> set) {
		final StandardCacheConfig<Integer, String> conf = new StandardCacheConfig<>();
		conf.setMaxKiloBytesLocalHeap(1L);
		conf.setDiskStorageMB(5L);
		conf.setTimeToLiveSeconds(2);
		conf.setName("XXX" + i);
		conf.setKeyClass(Integer.class);
		conf.setValueClass(String.class);
		conf.setLoader(key -> {
			set.add(key);
			try {
				Thread.sleep(30);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			return "KEY:" + key;
		});
		buildCache(conf.getName(), conf);
	}

	// CHECKSTYLE OFF 1
	private <K, V> void buildCache(String name, StandardCacheConfig<K, V> config) {
		ResourcePoolsBuilder resourcePoolsBuilder = ResourcePoolsBuilder.newResourcePoolsBuilder();
		if (config.getMaxEntriesLocalHeap() != null) {
			resourcePoolsBuilder = resourcePoolsBuilder.heap(config.getMaxEntriesLocalHeap(), EntryUnit.ENTRIES);
		}
		if (config.getMaxKiloBytesLocalHeap() != null) {
			resourcePoolsBuilder = resourcePoolsBuilder.heap(config.getMaxKiloBytesLocalHeap(), MemoryUnit.KB);
		}
		if (config.getDiskStorageMB() != null) {
			resourcePoolsBuilder = resourcePoolsBuilder.disk(config.getDiskStorageMB(), MemoryUnit.MB, false);
		}

		CacheConfiguration<K, V> cacheConfiguration = CacheConfigurationBuilder.newCacheConfigurationBuilder(
				config.getKeyClass(),
				config.getValueClass(),
				resourcePoolsBuilder
		)
				.withDiskStoreThreadPool("defaultPool", 3)
				.withExpiry(Expirations.timeToLiveExpiration(Duration.of(config.getTimeToLiveSeconds(), TimeUnit.SECONDS)))
				.withLoaderWriter(new CacheLoaderWriter<K, V>() {
					@Override
					public V load(K k) throws Exception {
						return config.getLoader().load(k);
					}

					@Override
					public Map<K, V> loadAll(Iterable<? extends K> iterable) throws BulkCacheLoadingException, Exception {
						return null;
					}

					@Override
					public void write(K k, V v) throws Exception {

					}

					@Override
					public void writeAll(Iterable<? extends Map.Entry<? extends K, ? extends V>> iterable) throws BulkCacheWritingException, Exception {

					}

					@Override
					public void delete(K k) throws Exception {

					}

					@Override
					public void deleteAll(Iterable<? extends K> iterable) throws BulkCacheWritingException, Exception {

					}
				})
				.build();
		cacheManager.createCache(name, cacheConfiguration);
	}

	// CHECKSTYLE ON 1
	private void initCacheManager() {
		cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
				.using(
						PooledExecutionServiceConfigurationBuilder
								.newPooledExecutionServiceConfigurationBuilder()
								.defaultPool("defaultPool", 1, 10)
								.build()
				)
				.with(CacheManagerBuilder.persistence("./target/cache"))
				.withDefaultDiskStoreThreadPool("defaultPool")
				.build();
		cacheManager.init();
	}
}
```

**Comment by henri-tremblay** [comment] 2017-03-09 21:42
I confirm it now works. Duplicate of #1598

**Closed by henri-tremblay** 2017-03-09 21:42 UTC

**Comment by henri-tremblay** [comment] 2017-03-10 04:41
Some missing classes to replicate:

```java
public interface CacheLoader<K, V> {
  V load(K value);
}

public class StandardCacheConfig<K, V> {
  private Long maxKiloBytesLocalHeap;
  private Long diskStorageMB;
  private Integer timeToLiveSeconds;
  private String name;
  private Class<K> keyClass;
  private Class<V> valueClass;
  private CacheLoader<K, V> loader;
  private Long maxEntriesLocalHeap;

  public void setMaxKiloBytesLocalHeap(Long maxKiloBytesLocalHeap) {
    this.maxKiloBytesLocalHeap = maxKiloBytesLocalHeap;
  }

  public Long getMaxKiloBytesLocalHeap() {
    return maxKiloBytesLocalHeap;
  }

  public void setDiskStorageMB(Long diskStorageMB) {
    this.diskStorageMB = diskStorageMB;
  }

  public Long getDiskStorageMB() {
    return diskStorageMB;
  }

  public void setTimeToLiveSeconds(Integer timeToLiveSeconds) {
    this.timeToLiveSeconds = timeToLiveSeconds;
  }

  public Integer getTimeToLiveSeconds() {
    return timeToLiveSeconds;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public void setKeyClass(Class<K> keyClass) {
    this.keyClass = keyClass;
  }

  public Class<K> getKeyClass() {
    return keyClass;
  }

  public void setValueClass(Class<V> valueClass) {
    this.valueClass = valueClass;
  }

  public Class<V> getValueClass() {
    return valueClass;
  }

  public CacheLoader<K, V> getLoader() {
    return loader;
  }

  public void setLoader(CacheLoader<K, V> loader) {
    this.loader = loader;
  }

  public Long getMaxEntriesLocalHeap() {
    return maxEntriesLocalHeap;
  }

  public void setMaxEntriesLocalHeap(Long maxEntriesLocalHeap) {
    this.maxEntriesLocalHeap = maxEntriesLocalHeap;
  }
}
```

**Comment by bjanczak** [comment] 2017-03-10 06:53
Sorry:,
`package com.softwareplant.util.cacheint.multitenant;

import com.softwareplant.util.cache.CacheConfig;
import com.softwareplant.util.cache.CacheLoader;
import com.softwareplant.util.cache.OptionalCacheLoader;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

public class StandardCacheConfig<K, V> implements CacheConfig {

	private String name;

	private Long maxEntriesLocalHeap;

	private Long maxKiloBytesLocalHeap;

	private Long diskStorageMB;

	private long timeToLiveSeconds;

	private Class<K> keyClass;

	private Class<V> valueClass;

	private CacheLoader<K, V> loader = new OptionalCacheLoader<>();

	public String getName() {
		return name;
	}

	Long getMaxEntriesLocalHeap() {
		return maxEntriesLocalHeap;
	}

	public Long getMaxKiloBytesLocalHeap() {
		return maxKiloBytesLocalHeap;
	}

	Long getDiskStorageMB() {
		return diskStorageMB;
	}

	long getTimeToLiveSeconds() {
		return timeToLiveSeconds;
	}

	public CacheLoader<K, V> getLoader() {
		return loader;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setMaxEntriesLocalHeap(Long maxEntriesLocalHeap) {
		this.maxEntriesLocalHeap = maxEntriesLocalHeap;
	}

	public void setMaxKiloBytesLocalHeap(Long maxKiloBytesLocalHeap) {
		this.maxKiloBytesLocalHeap = maxKiloBytesLocalHeap;
	}

	public void setDiskStorageMB(Long diskStorageMB) {
		this.diskStorageMB = diskStorageMB;
	}

	public void setTimeToLiveSeconds(long timeToLiveSeconds) {
		this.timeToLiveSeconds = timeToLiveSeconds;
	}

	public void setLoader(CacheLoader<K, V> loader) {
		this.loader = loader;
	}

	public void setKeyClass(Class<K> keyClass) {
		this.keyClass = keyClass;
	}

	public void setValueClass(Class<V> valueClass) {
		this.valueClass = valueClass;
	}

	public Class<K> getKeyClass() {
		return keyClass;
	}

	public Class<V> getValueClass() {
		return valueClass;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}

		if (o == null || getClass() != o.getClass()) {
			return false;
		}

		StandardCacheConfig<?, ?> that = (StandardCacheConfig<?, ?>) o;

		return new EqualsBuilder()
				.append(timeToLiveSeconds, that.timeToLiveSeconds)
				.append(name, that.name)
				.append(maxEntriesLocalHeap, that.maxEntriesLocalHeap)
				.append(maxKiloBytesLocalHeap, that.maxKiloBytesLocalHeap)
				.append(diskStorageMB, that.diskStorageMB)
				.append(loader, that.loader)
				.isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(17, 37)
				.append(name)
				.append(maxEntriesLocalHeap)
				.append(maxKiloBytesLocalHeap)
				.append(diskStorageMB)
				.append(timeToLiveSeconds)
				.append(loader)
				.toHashCode();
	}

	@Override
	public String toString() {
		return new ToStringBuilder(this)
				.append("name", name)
				.append("maxEntriesLocalHeap", maxEntriesLocalHeap)
				.append("maxKiloBytesLocalHeap", maxKiloBytesLocalHeap)
				.append("diskStorageMB", diskStorageMB)
				.append("timeToLiveSeconds", timeToLiveSeconds)
				.append("loader", loader.getClass().getName())
				.toString();
	}
}
`
