### ISSUE TITLE
Ehcache master build failing

### ISSUE THREAD

**Issue by AbfrmBlr** [ehcache/ehcache3#2296] opened 2018-02-19 07:54 UTC
```
2018-02-17 16:56:54,255 [WorkerThread(request_processor_during_sync_stage, 1, 1)] ERROR com.tc.objectserver.entity.ManagedEntityImpl - caught exception during invoke 
java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.ehcache.clustered.server.store.ClusterTierActiveEntity.synchronizeKeyToPassive(ClusterTierActiveEntity.java:604)
	at com.tc.objectserver.entity.ManagedEntityImpl.performSync(ManagedEntityImpl.java:788)
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:567)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$sync$22(ManagedEntityImpl.java:1081)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:194)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:185)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:28)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:24)
	at com.tc.async.impl.StageImpl.lambda$null$1(StageImpl.java:107)
	at com.tc.async.impl.MonitoringEventCreator.lambda$createEvent$0(MonitoringEventCreator.java:77)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:285)
2018-02-17 16:56:54,256 [WorkerThread(request_processor_during_sync_stage, 1, 1)] ERROR com.tc.async.api.Stage: request_processor_during_sync_stage - Uncaught exception in stage
java.lang.RuntimeException: java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:588)
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$sync$22(ManagedEntityImpl.java:1081)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:194)
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:185)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:28)
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:24)
	at com.tc.async.impl.StageImpl.lambda$null$1(StageImpl.java:107)
	at com.tc.async.impl.MonitoringEventCreator.lambda$createEvent$0(MonitoringEventCreator.java:77)
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:285)
Caused by: java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.ehcache.clustered.server.store.ClusterTierActiveEntity.synchronizeKeyToPassive(ClusterTierActiveEntity.java:604)
	at com.tc.objectserver.entity.ManagedEntityImpl.performSync(ManagedEntityImpl.java:788)
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:567)
	... 8 common frames omitted
```

**Comment by AbfrmBlr** [comment] 2018-02-19 07:55
https://ehcache.ci.cloudbees.com/job/ehcache3/1579/jdk=Oracle%20JDK%201.8(latest),label_exp=standard,testVM=8/testReport/junit/org.ehcache.clustered.replication/BasicClusteredCacheOpsReplicationMultiThreadedTest/

**Comment by chrisdennis** [comment] 2019-02-22 00:28
@lmerckx what version were you using when you saw this?

**Comment by lmerckx** [comment] 2019-02-22 08:24
@chrisdennis It was 3.6.1 (clustered)

**Comment by chrisdennis** [comment] 2019-02-22 20:16
Fixed in https://github.com/ehcache/ehcache3/pull/2587

**Closed by chrisdennis** 2019-02-22 20:16 UTC
Labels: bug, clustering, prioritized

**Comment by rajendarg** [comment] 2019-05-21 17:54
I also got the error with version 3.7.1 (cluster api) with 3.7.0 terracotta server

Server A starts (as active)
Server B starts (as passive)
Server A is stopped, B becomes active
Server A is restarted ... server B crashes with above exception when synchronizing


2019-05-21 23:08:30,397 [main] INFO com.tc.l2.logging.TCLogbackLogging - Log file: /root/failover-server-logs/terracotta.server.log
2019-05-21 23:08:30,408 INFO - Available Max Runtime Memory: 1822MB
2019-05-21 23:08:30,487 WARN - Running the server in AVAILABILITY mode with the risk of split brain scenarios.
2019-05-21 23:08:30,829 INFO - NodeID[172.16.1.23:9410] joined the cluster
2019-05-21 23:08:30,834 INFO - Moved to State[ PASSIVE-UNINITIALIZED ]
2019-05-21 23:08:30,835 INFO - Moved to State[ PASSIVE-SYNCING ]
2019-05-21 23:08:30,920 INFO - Moved to State[ PASSIVE-STANDBY ]

[root@appserver bin]# 2019-05-21 23:12:35,070 WARN - NodeID[172.16.1.23:9410] left the cluster
2019-05-21 23:12:40,071 INFO - Becoming State[ ACTIVE-COORDINATOR ]
2019-05-21 23:12:40,087 INFO - Starting reconnect window: 120000 ms. Waiting for 1 clients to connect. Unconnected Clients - [ClientID[10]]
2019-05-21 23:12:40,087 INFO - Terracotta Server instance has started up as ACTIVE node on 0:0:0:0:0:0:0:0:9410 successfully, and is now ready for work.
2019-05-21 23:13:18,126 INFO - NodeID[172.16.1.23:9410] joined the cluster
com.tc.exception.TCRuntimeException: Uncaught exception in stage
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:307)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
        at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:611)
        at com.tc.objectserver.entity.ManagedEntityImpl.lambda$sync$22(ManagedEntityImpl.java:1110)
        at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:194)
        at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:185)
        at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:28)
        at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:24)
        at com.tc.async.impl.StageImpl.lambda$null$1(StageImpl.java:105)
        at com.tc.async.impl.MonitoringEventCreator.lambda$createEvent$0(MonitoringEventCreator.java:77)
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:284)
Caused by: java.lang.ClassCastException: org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage cannot be cast to org.ehcache.clustered.server.internal.messages.EhcacheStateRepoSyncMessage
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.ehcache.clustered.server.store.ClusterTierActiveEntity.synchronizeKeyToPassive(ClusterTierActiveEntity.java:650)
        at com.tc.objectserver.entity.ManagedEntityImpl.performSync(ManagedEntityImpl.java:814)
        at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:590)
        ... 8 more
2019-05-21 23:13:18,534 [WorkerThread(request_processor_during_sync_stage, 0, 0)] INFO org.terracotta.dump - [dump] {
  className=com.tc.async.impl.StageManagerImpl
  monitor=false
  stages=[
    {
      name=single_threaded_fastpath
