### ISSUE TITLE
Have the ResilienceStrategy as a Service, so that we can override it

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#2095] opened 2017-08-25 20:59 UTC
In Ehcache, around line #126 , we hard-wire the ResilienceStrategy : 
```
    if (store instanceof RecoveryCache) {
      this.resilienceStrategy = new LoggingRobustResilienceStrategy<K, V>(castToRecoveryCache(store));
    } else {
      this.resilienceStrategy = new LoggingRobustResilienceStrategy<K, V>(recoveryCache(store));
    }
```

It would be interesting to be able to customize the ResilienceStrategy, passing it as a service; an example of ResilienceStrategy would be "ThroughRuntimeExceptionResilienceStrategy" or "SendSMSResilienceStrategy"

**Comment by ljacomet** [comment] 2017-08-28 08:21
Closing as duplicate of #52 - this is indeed the plan

**Closed by ljacomet** 2017-08-28 08:21 UTC
Labels: usability
