### ISSUE TITLE
Add different loader writer resilience strategies

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#2200] opened 2017-12-05 17:13 UTC
Add different loader writer resilience strategy. Move it to the API
- The current one
- The NOP one
- The always failing one (decide if it should be the default)

Requires #2198

**Comment by chrisdennis** [comment] 2022-11-30 20:17
This becomes a duplicate of #2199 if we improve the abstract super class support.

**Closed by chrisdennis** 2022-11-30 20:17 UTC
Labels: enhancement, prioritized, resilience, pending review
