### ISSUE TITLE
Failing test preventing PR build: ClusteredStateRepositoryReplicationTest.testClusteredStateRepositoryReplication

### ISSUE THREAD

**Issue by mathieucarbou** [ehcache/ehcache3#1677] opened 2016-12-03 17:33 UTC
When running locally, I run across this failing test:

`ClusteredStateRepositoryReplicationTest.testClusteredStateRepositoryReplication`

When it fails, the build stops. I don't know why.

This prevent PR #1676 to build.

```
[Server thread isActive: active] INFO org.ehcache.clustered.server.EhcacheActiveEntity - Connecting PassthroughClientDescriptor{server=org.terracotta.passthrough.PassthroughServerProcess@2972c7e7, sender=org.terracotta.passthrough.PassthroughConnection@6c70440d, clientInstanceID=2}
[Server thread isActive: active] INFO org.ehcache.clustered.server.EhcacheStateServiceImpl - Configuring server-side clustered tier manager
[Server thread isActive: active] INFO org.ehcache.clustered.server.EhcacheActiveEntity - Disconnecting PassthroughClientDescriptor{server=org.terracotta.passthrough.PassthroughServerProcess@2972c7e7, sender=org.terracotta.passthrough.PassthroughConnection@6c70440d, clientInstanceID=2}
[Server thread isActive: active] INFO org.ehcache.clustered.server.EhcacheActiveEntity - Connecting PassthroughClientDescriptor{server=org.terracotta.passthrough.PassthroughServerProcess@2972c7e7, sender=org.terracotta.passthrough.PassthroughConnection@6c70440d, clientInstanceID=4}
[Server thread isActive: active] INFO org.ehcache.clustered.server.EhcacheActiveEntity - Adding Client PassthroughClientDescriptor{server=org.terracotta.passthrough.PassthroughServerProcess@2972c7e7, sender=org.terracotta.passthrough.PassthroughConnection@6c70440d, clientInstanceID=4} with client ID : 7617ad1a-deba-4202-a63d-ad93ff9aa661 
FATAL EXCEPTION IN PASSTHROUGH THREAD:
java.lang.AssertionError: Unexpected exception
	at org.terracotta.passthrough.Assert.unexpected(Assert.java:28)
	at org.terracotta.passthrough.PassthroughServerProcess.reconnect(PassthroughServerProcess.java:784)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:307)
	at org.terracotta.passthrough.PassthroughServerMessageDecoder.decode(PassthroughServerMessageDecoder.java:37)
	at org.terracotta.passthrough.PassthroughMessageCodec.runRawDecoder(PassthroughMessageCodec.java:344)
	at org.terracotta.passthrough.PassthroughMessageCodec.decodeRawMessage(PassthroughMessageCodec.java:267)
	at org.terracotta.passthrough.PassthroughServerProcess.serverThreadHandleMessage(PassthroughServerProcess.java:497)
	at org.terracotta.passthrough.PassthroughServerProcess.runServerThread(PassthroughServerProcess.java:473)
	at org.terracotta.passthrough.PassthroughServerProcess.access$000(PassthroughServerProcess.java:78)
	at org.terracotta.passthrough.PassthroughServerProcess$2.run(PassthroughServerProcess.java:251)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Entity not found in reconnect
	... 10 more
```

![screen shot 2016-12-03 at 12 30 16](https://cloud.githubusercontent.com/assets/61346/20861060/9e5ce538-b954-11e6-8b3a-a139a9e061da.png)

**Comment by mathieucarbou** [comment] 2016-12-03 18:13
FYI, this bug is created by https://github.com/Terracotta-OSS/tc-passthrough-testing/issues/58

As a workaround, I'll do a null-check after this like in `Monitoring`:

`IMonitoringProducer monitoringProducer = services.getService(new BasicServiceConfiguration<>(IMonitoringProducer.class));`

This will make PR #1676 pass.

But this won't resolve the issue: `IMonitoringProducer` should always be there: this is a platform-provided service.

**Comment by ljacomet** [comment] 2016-12-05 08:22
Closing since the root cause is in a dependency

**Closed by ljacomet** 2016-12-05 08:22 UTC
Labels: blocked, bug, in progress
