### ISSUE TITLE
New active crashes after faillover when clients reconnect

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1666] opened 2016-11-30 17:23 UTC
Here is the assertion error that crashes active,

com.tc.util.TCAssertionError: entity not found
at com.tc.util.Assert.failure(Assert.java:55)
at com.tc.util.Assert.failure(Assert.java:55)
at com.tc.objectserver.handshakemanager.ServerClientHandshakeManager.notifyClientConnect(ServerClientHandshakeManager.java:138)
at com.tc.objectserver.handshakemanager.ServerClientHandshakeManager.notifyClientConnect(ServerClientHandshakeManager.java:138)
at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:68)
at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:68)
at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:38)
at com.tc.objectserver.handler.ClientHandshakeHandler.handleEvent(ClientHandshakeHandler.java:38)
at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

Here is the test case to reproduce this issue.

    CLUSTER.getClusterControl().waitForActive();
    //Create two cache manager clients connecting to same entity on server.
    PersistentCacheManager[] cacheManagers = new PersistentCacheManager[2];
    for (int i = 0; i < cacheManagers.length; ++i) {
      CacheManagerBuilder<PersistentCacheManager> builder = CacheManagerBuilder.newCacheManagerBuilder()
        .with(ClusteringServiceConfigurationBuilder.cluster(CLUSTER.getConnectionURI()
          .resolve("/crud-cm-replication"))
          .autoCreate()
          .defaultServerResource("primary-server-resource")
          .resourcePool("resource-pool-a", 8, MemoryUnit.MB));
      cacheManagers[i] = builder.build(true);

    }

    cacheManagers[0].close();
    try {
      //Destroy cache manager when other client "1" still connected to it.
      cacheManagers[0].destroy();
      Assert.fail("Expected error not thrown");
    } catch (StateTransitionException e) {
      //expected
    }

    //failover
    CLUSTER.getClusterControl().terminateActive();
    CLUSTER.getClusterControl().waitForActive();
    Assert.assertNotNull(cacheManagers[1].createCache("cache1", CacheConfigurationBuilder.newCacheConfigurationBuilder(Integer.class, Integer.class,
      ResourcePoolsBuilder.newResourcePoolsBuilder()
        .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 8, MemoryUnit.MB)))
      .add(ClusteredStoreConfigurationBuilder.withConsistency(Consistency.EVENTUAL))));

**Comment by ljacomet** [comment] 2016-12-01 13:16
Confirmed the issue, seems linked to our rapid create / destroy / create of the locking entity we use for exclusive access to the clustered tier manager entity.

**Comment by ljacomet** [comment] 2016-12-02 13:32
Root cause is Terracotta-OSS/terracotta-core#379. I will however push a fix that will make it occurence much less likely in order to have a better stability while the root cause gets fixed.

**Comment by myronkscott** [comment] 2016-12-02 16:03
Fix for Terracotta-OSS/terracotta-core#379 has been merged and will be included in the next release.

**Closed** 2016-12-12 22:51 UTC
Labels: bug, clustering, in progress
