### ISSUE TITLE
cache always returns null if using heap + MemoryUnit

### ISSUE THREAD

**Issue by fmq** [ehcache/ehcache3#1955] opened 2017-04-08 00:54 UTC
Hi

If I create a cache with a MemoryUnit limit it always returns empty (aka nothing get's stored).

So this does not work:

```
CacheManager cacheManager
                = CacheManagerBuilder.newCacheManagerBuilder()
                .withCache(FRMLAB_CACHE_ALIAS,
                        CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, Map.class,
                                ResourcePoolsBuilder.newResourcePoolsBuilder()
                                        .heap(10L, MemoryUnit.MB))).build();
        cacheManager.init();
```

But this works just fine
```
CacheManager cacheManager
                = CacheManagerBuilder.newCacheManagerBuilder()
                .withCache(FRMLAB_CACHE_ALIAS,
                        CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, Map.class,
                                ResourcePoolsBuilder.newResourcePoolsBuilder()
                                        .heap(10L))).build();
        cacheManager.init();
```

The test is simple 

store with 
```
cache.put();
```

and test if it's there with:

```
if (cache.containsKey(formId)) {} 
```

What am I doing wrong?

Regards

**Comment by henri-tremblay** [comment] 2017-04-08 01:12
In general, we ask to discuss issues on the mailing list before filing a bug.

Anyway, I looked at you issue and the answer is: I don't know. Which Ehcache version are you using? I tried with 3.3.1 and it worked perfectly.

BTW, these two methods are not doing the same thing. The one with a single parameter is limiting the cache to 10 entries. The other is limiting the cache to 10MB.

Here is my full test:

```java
  @Test
  public void test() {
    CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
      .withCache(FRMLAB_CACHE_ALIAS,
        CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, Map.class,
          ResourcePoolsBuilder.newResourcePoolsBuilder()
            .heap(10L, MemoryUnit.MB))).build();
    cacheManager.init();

    Cache<String, Map> cache = cacheManager.getCache(FRMLAB_CACHE_ALIAS, String.class, Map.class);
    cache.put("allo", Collections.emptyMap());
    assertThat(cache.containsKey("allo")).isTrue();
  }
```

**Comment by fmq** [comment] 2017-04-08 01:38
Hello

First, I'm sorry about the mailing list.. did not know... I will move this there but just to clarify with you a couple of things:

1. The idea was to user the memory limit not the count limit, this is why I'm attempting to set the cache up using MemoryUnit.MB
2. This actually works fine (as in your test) i f I query the cache right after I insert the data. The problem is this is part of a service that is used to store database data for faster access and is called from a REST service and the problem is between invocations. In the second invocation the cache is empty.

This is my full cache class

```
@Named("formLabelCache")
@ApplicationScoped
public class FormLabelCache {

    Logger logger = Logger.getLogger(FormLabelCache.class.getCanonicalName());

    Cache<String, Map> cache;

    private static final String FRMLAB_CACHE_ALIAS = "dmfas.cache.formLabel";

    @PostConstruct
    public void init() {

        logger.info("Starting module group rels cache..");

        CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
                .withCache(FRMLAB_CACHE_ALIAS,
                        CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, Map.class,
                                ResourcePoolsBuilder.newResourcePoolsBuilder()
                                        .heap(10L, MemoryUnit.MB))).build();
        cacheManager.init();

        // get the cache
        cache = cacheManager.getCache(FRMLAB_CACHE_ALIAS,String.class, Map.class);

    }

    public void addLables(String formId, List<FormLabel> labels) {

        Map<Integer, List<FormLabel>> labelMap = new HashMap<Integer, List<FormLabel>>();

        for (FormLabel label: labels) {
            if (!labelMap.containsKey(label.getLaId()))
                labelMap.put(label.getLaId(), new ArrayList<FormLabel>());
            labelMap.get(label.getLaId()).add(label);
        }
        logger.log(Level.FINE, "Adding labels for form {0}", formId);
        cache.put(formId,labelMap);
        
        if (cache.containsKey(formId)) {
            logger.log(Level.FINE, "FOUND {0}", formId);
        }
    }

    public  List<FormLabel> getCodes(String formId, int laId) {
        
        if (cache.containsKey(formId)) {
            Map<String, List<FormLabel>> data = (Map<String, List<FormLabel>>) cache.get(formId).get(laId);
            return data.get(laId);
        }

        return null;
    }

}
```

Again

Sorry for the mailing list.

Regards

**Comment by henri-tremblay** [comment] 2017-04-08 05:02
I still can't reproduce it locally.

However, I see two things here:
- I'm a bit frightened by the `CacheManager` being a local variable. Can you please put it as an attribute of `FormLabelCache`? You can call `close` on it in a `@PreDestroy` method
- Are you sure you never get above 10MB? Because that would discard your entries

**Comment by fmq** [comment] 2017-04-09 04:20
Well.. it definitely has something to do with size since i'm getting

```
2017-04-09 01:10:13,884 INFO  [org.unctad.dmfas.service.i18n.cache.FormLabelCache] (default task-2) Adding labels for form frmDebtServices .. added: 363 labels
2017-04-09 01:10:13,894 WARN  [org.ehcache.impl.internal.store.heap.OnHeapStore] (default task-2) Max Object Graph Size reached for the object : [C@614ce1e
```

I'm pretty sure I'm not reaching the 1GM limit I gave it for test purposes so the problem must be with storing a List in the cache (and it's size). 

I will read a bit more and try and figure out whats happening.

Thanks for your help!

**Comment by henri-tremblay** [comment] 2017-04-10 04:30
Oh! I get it. Ehcache might refuse to cache objects that are too big to be sized. This is the "Max Object Size reached" warning you see. By default it is 1000. You can read more about it [here](http://www.ehcache.org/documentation/3.3/tiering.html#byte-sized-heap). We do this because sizing has a performance hit on big objects.

In your case, you can decide to size in entries (so no sizing occurs) or to set the max graph a bit higher.

**Comment by henri-tremblay** [comment] 2017-04-10 13:36
I will close this has "Not a bug" since the issue seems to be the object graph size. I've create #1956  to mention the defaults in the documentation.

**Closed by henri-tremblay** 2017-04-10 13:36 UTC
Labels: bug

**Comment by fmq** [comment] 2017-04-10 14:50
Yes.. 

Sorry I was caught up with something else.. I read through the doc you sent me and will try and figure out if my approach is correct, If I have any more questions on this I will go through the email list first!! 

Thank you very much for your help!

Regards
