### ISSUE TITLE
Closing a clustered CacheManager will wait indefinitely if the server is down

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#2283] opened 2018-02-12 20:06 UTC
Just try to close a `CacheManager` connected to a clustered cache when the server is down. It will wait forever.

```
  @Test
  public void testTerminationFreezesTheClient() throws Exception {
    Duration readOperationTimeout = Duration.ofMillis(100);

    try(PersistentCacheManager cacheManager =
          CacheManagerBuilder.newCacheManagerBuilder()
            .with(ClusteringServiceConfigurationBuilder.cluster(cluster.getConnectionURI().resolve("/MyCacheManagerName"))
              .timeouts(TimeoutsBuilder.timeouts()
                .read(readOperationTimeout))
              .autoCreate()
              .defaultServerResource("primary-server-resource"))
            .withCache("simple-cache",
              CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, String.class,
                ResourcePoolsBuilder.newResourcePoolsBuilder()
                  .with(ClusteredResourcePoolBuilder.clusteredDedicated(4, MemoryUnit.MB))))
            .build(true)) {

      cluster.getClusterControl().terminateAllServers();
    }
  }
```

 Ideally, it should timeout when the lease expires.

**Comment by chrisdennis** [comment] 2019-02-14 15:22
This is probably caused by #2473 ... whoever investigates this should validate this and close together if necessary.

**Comment by chrisdennis** [comment] 2022-11-16 20:18
See the semi-duplicate #2473 for more information.

**Comment by nnares** [comment] 2023-02-02 13:54
I have tried to reproduce this issue, here is my observation :
1. CacheManager closing thread is not waiting forever
2. Once connection gets closed and client thread try to clone the cache manager :
	it try to reconnect (120Sec default setting) - which gets failed
	once it exceeds leasing duration (150sec default setting) - lease lost has happened
	client thread then try to close the connection to cluster, during that 
        client thread is getting - org.terracotta.exception.ConnectionClosedException

**Comment by nnares** [comment] 2023-02-03 16:41
No Longer this is reproducible, So closing this issue.

**Closed by nnares** 2023-02-03 16:41 UTC
Labels: bug, resilience
