### ISSUE TITLE
com.tc.util.TCAssertionError: Unexpected exception executing replicated message

### ISSUE THREAD

**Issue by kcleereman** [ehcache/ehcache3#1706] opened 2016-12-12 17:52 UTC
I occasionally encounter this error when starting a passive server after having loaded the active server for five minutes.

com.tc.util.TCAssertionError: Unexpected exception executing replicated message
        at com.tc.util.Assert.failure(Assert.java:41)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler$2.handleEvent(ReplicatedTransactionHandler.java:116)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler$2.handleEvent(ReplicatedTransactionHandler.java:108)
        at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
        at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
Caused by: com.tc.util.TCAssertionError: Assertion failed: ReplicationMessage{rid=1, activity=SyncReplicationActivity{id=EntityID{className='org.ehcache.clustered.client.internal.EhcacheClientEntity', entityName='cachemanager'}, src=ClientID[0], tid=TransactionID=[29696659], oldest=TransactionID=[29696526], action=NOOP, concurrency=-2147483648, debug=}}
        at com.tc.util.Assert.failure(Assert.java:55)
        at com.tc.util.Assert.eval(Assert.java:75)
        at com.tc.util.Assert.assertTrue(Assert.java:95)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler$SyncState.assertStarted(ReplicatedTransactionHandler.java:727)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler$SyncState.ignore(ReplicatedTransactionHandler.java:647)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler$SyncState.access$700(ReplicatedTransactionHandler.java:582)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler.processMessage(ReplicatedTransactionHandler.java:185)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler.access$200(ReplicatedTransactionHandler.java:72)
        at com.tc.objectserver.handler.ReplicatedTransactionHandler$2.handleEvent(ReplicatedTransactionHandler.java:112)

**Comment by kcleereman** [comment] 2016-12-12 17:53
[assertion.txt](https://github.com/ehcache/ehcache3/files/646758/assertion.txt)

**Comment by ljacomet** [comment] 2016-12-13 18:36
The root cause was terracotta-oss/terracotta-core#393 and it has been fixed so closing.

**Closed by ljacomet** 2016-12-13 18:36 UTC
