### ISSUE TITLE
JSR107 cache manager configuration fails to parse on apache karaf

### ISSUE THREAD

**Issue by exmortal** [ehcache/ehcache3#466] opened 2015-07-21 11:50 UTC
Hi, 

I want to add EHCache v3 JSR107 provider running on apache karaf platform. I use https://ehcache.github.io/docs/user/3.0/107.html as a howto tutorial.
Cache manager fails to create when I try to create it based on xml configuration. I use configuration file form the tutorial. 

Here is an exception:

Caused by: java.lang.ClassCastException: org.apache.xerces.dom.TextImpl cannot be cast to org.w3c.dom.Element
	at org.ehcache.jsr107.ServiceConfigParser.parse(ServiceConfigParser.java:61)
	at org.ehcache.config.xml.ConfigurationParser.parseExtension(ConfigurationParser.java:446)
	at org.ehcache.config.xml.ConfigurationParser.getServiceConfigurations(ConfigurationParser.java:125)
	at org.ehcache.config.xml.XmlConfiguration.parseConfiguration(XmlConfiguration.java:139)
	at org.ehcache.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:130)
	at org.ehcache.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:105)
	at org.ehcache.jsr107.EhcacheCachingProvider.getCacheManager(EhcacheCachingProvider.java:87)
	... 86 more

Debug shows me that there is an empty element exists just after jsr107:cache item and it can't be cast to the org.w3c.dom.Element. Element contains "\n  ".  

Moreover, unit test of the same code works correctly. 

Thanks,
Vlad

**Comment by chrisdennis** [comment] 2015-07-24 20:09
To me it sounds like you might have managed to slip an invalid piece of configuration past the XML parsing/validation.  If you could paste the exact content of your config file here, or link to a gist that would be a great first step here.

**Comment by exmortal** [comment] 2015-07-27 15:50
here is my echcache.xml:

<config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xmlns='http://www.ehcache.org/v3'
        xmlns:jsr107='http://www.ehcache.org/v3/jsr107'>

    <service>
        <jsr107:defaults default-template="defaultCache">
            <jsr107:cache name="cache_default" template="defaultCache"/>
        </jsr107:defaults>
    </service>

    <cache-template name="defaultCache">
        <heap size="10000" unit="entries"/>
    </cache-template>
</config>

**Comment by exmortal** [comment] 2015-07-27 15:56
Here is my echcache.xml:

```javascript
<config xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xmlns='http://www.ehcache.org/v3'
        xmlns:jsr107='http://www.ehcache.org/v3/jsr107'>

    <service>
        <jsr107:defaults default-template="defaultLocalCache">
            <jsr107:cache name="system_default" template="defaultLocalCache"/>
        </jsr107:defaults>
    </service>

    <cache-template name="defaultLocalCache">
        <heap size="10000" unit="entries"/>
    </cache-template>
</config>
```

**Comment by lorban** [comment] 2015-07-28 13:57
A deeper analysis made me conclude that this is caused by an incompatibility between java.util.ServiceLoader and OSGi.

What happens is that the ConfigurationParser class tries to load the XmlConfigurationParser service but OSGi seems to silently prevent that in such a way that we end up building an empty schemaSources array that we pass to the DocumentBuilderFactory.

Without a schema, the ' ', '\t', '\r' and '\n' characters are treated as text by the parser instead of being ignored, eventually causing the reported exception.

It looks like this problem can be solved by editing the manifest with some OSGi-specific properties (see http://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html).

**Comment by exmortal** [comment] 2015-08-05 16:16
Hi @lorban. I have echache v3 jar embedded in my bundle, so OSGi service loader mediator won't help.

**Comment by exmortal** [comment] 2015-08-13 13:37
I guess I found the problem. 

Apache Karaf contains an artifact of xercesImpl-2.11.0.jar in a karaf/lib/endorsed folder
karaf says "Any jar in this folder will be used to override classes defined by the JVM." 
Hence configuration failed to be parsed cause wrong version of xml parser is used.

BTW: schema resolution is working OK.

**Comment by alexsnaps** [comment] 2015-08-18 14:07
@exmortal can you check the fix that was merged to master fixes the problem for you? 
You should be able to test this with the latest `-SNAPSHOT`

**Comment by exmortal** [comment] 2015-08-19 14:25
@alexsnaps, seems to be ok now, thanks. I'll be waiting for next release.

**Comment by alexsnaps** [comment] 2015-08-19 14:55
Awesome! Thanks... I'm closing this then.

**Closed by alexsnaps** 2015-08-19 14:55 UTC
Labels: bug, in progress
