### ISSUE TITLE
Exception when retrieving from cache after restart

### ISSUE THREAD

**Issue by esebasti** [ehcache/ehcache3#1351] opened 2016-07-28 21:01 UTC
Here is the exception. This can be reproduced by the attached test case which runs user managed persistent cache  without any custom serializers.

Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.ehcache.impl.serialization.CompactJavaSerializer$OIS.readClassDescriptor(CompactJavaSerializer.java:239)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1602)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.ehcache.impl.serialization.CompactJavaSerializer.read(CompactJavaSerializer.java:131)
	at org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.forceDeserialization(LazyOffHeapValueHolder.java:99)
	at org.ehcache.impl.internal.store.offheap.LazyOffHeapValueHolder.value(LazyOffHeapValueHolder.java:53)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.cloneValueHolder(OnHeapStore.java:1459)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.importValueFromLowerTier(OnHeapStore.java:1449)
	at org.ehcache.impl.internal.store.heap.OnHeapStore.getOrComputeIfAbsent(OnHeapStore.java:707)

**Comment by esebasti** [comment] 2016-07-28 21:54
Test case snippet.

    File folder = temporaryFolder.newFolder("cache-persistence-store");
    {
      LocalPersistenceService persistenceService = new DefaultLocalPersistenceService(new DefaultPersistenceConfiguration(folder));
      PersistentUserManagedCache<Long, Foo> cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(Long.class, Foo.class)
          .with(new UserManagedPersistenceContext<Long, Foo>("cache-name", persistenceService))
          .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
              .heap(10L, EntryUnit.ENTRIES)
              .disk(10L, MemoryUnit.MB, true))
          .build(true);
      cache.put(1L, new Foo(1));
      Assert.assertNotNull(cache.get(1L));
      cache.close();
      persistenceService.stop();
    }

    {
      LocalPersistenceService persistenceService = new DefaultLocalPersistenceService(new DefaultPersistenceConfiguration(folder));
      PersistentUserManagedCache<Long, Foo> cache = UserManagedCacheBuilder.newUserManagedCacheBuilder(Long.class, Foo.class)
          .with(new UserManagedPersistenceContext<Long, Foo>("cache-name", persistenceService))
          .withResourcePools(ResourcePoolsBuilder.newResourcePoolsBuilder()
              .heap(10L, EntryUnit.ENTRIES)
              .disk(10L, MemoryUnit.MB, true))
          .build(true);
      //It fails here
      Assert.assertNotNull(cache.get(1L));
      cache.close();
      persistenceService.stop();
      cache.destroy();
    }

**Comment by ljacomet** [comment] 2016-08-01 10:13
Closed as duplicate of #1298

**Closed by ljacomet** 2016-08-01 10:13 UTC
Labels: duplicate
