### ISSUE TITLE
Voltron read write unlock should be with timeout

### ISSUE THREAD

**Issue by rkavanap** [ehcache/ehcache3#2473] opened 2018-08-29 09:29 UTC
unlock() is now used in the close path and in order to make the close() path more predictable, unlock() should have a timeout.

This should ideally be the case for all voltron lock entity operations so that client(s) will not hang on any part of the lifecycle if there are some network or server side issues.

**Comment by chrisdennis** [comment] 2022-11-16 20:08
I "feel" like this should be handled by the leasing logic. If the connection is paused/stalled for whatever reason then the leasing logic will tear the connection down. I'm not sure if this is good enough, but it might be. We should assess how appropriate this is (or isn't).

**Comment by chrisdennis** [comment] 2022-11-16 20:18
Closing as duplicate of #2283

**Closed by chrisdennis** 2022-11-16 20:18 UTC
Labels: bug
