### ISSUE TITLE
Need tests that verify that the 107 config extensions work correctly

### ISSUE THREAD

**Issue by timeck** [ehcache/ehcache3#216] opened 2014-12-09 21:32 UTC
This mechanism lets one associate 107 caches to either a default cache template or to a specific template for a specific 107 cache name. 

In either case there is no test for this at the moment.

One thing to definitely assert is that all of the overlap between 107 config and ehcache config is applied. Things like expiration, loader/writer, expiry, etc should also be dictated by the 107 (always overriding what might be present in the 107 template config)

**Comment by sreekanth-r** [comment] 2015-01-08 09:13
JSR 107 Cache Configuration classes i.e. `Eh107CompleteConfiguration` & `Eh107ReverseConfiguration` doesn't expose

* Runtime Configuration (i.e. way to checking configured Capacity)
* Eviction veto
* Eviction Priotirizer

Should these be exposed for unit testing purpose?

**Comment by ljacomet** [comment] 2015-01-15 20:09
Following the discussions during today's public dev meeting, before looking at the two types you mention, we need to figure out what happens when you have values in the XML template and you pass in a `MutableConfiguration` with minimal things setup on it.
Could you write some code showing that and then revive the discussion?

**Comment by sreekanth-r** [comment] 2015-01-16 04:19
JSR 107 Configuration with template

```

<ehcache:config
    xmlns:ehcache="http://www.ehcache.org/v3"
    xmlns:jcache="http://www.ehcache.org/v3/jsr107">

  <!-- Defining a default template cache which stores long, string mapping -->
  <ehcache:service>
    <jcache:defaults default-template="defaultTemplate">
      <jcache:cache name="productCache" template="productCacheTemplate"/>
    </jcache:defaults>
  </ehcache:service>

  <ehcache:cache-template name="defaultTemplate" storeByValueOnHeap="true">
    <ehcache:key-type>java.lang.Long</ehcache:key-type>
    <ehcache:value-type>java.lang.String</ehcache:value-type>
    <ehcache:capacity>2</ehcache:capacity>
    <ehcache:expiry>
      <ehcache:ttl unit="millis">1</ehcache:ttl>
    </ehcache:expiry>
    <ehcache:eviction-prioritizer>LRU</ehcache:eviction-prioritizer>
  </ehcache:cache-template>

  <!-- product cache template overriding all properties from default -->
  <ehcache:cache-template name="productCacheTemplate" storeByValueOnHeap="false">
    <ehcache:key-type>java.lang.Long</ehcache:key-type>
    <ehcache:value-type>com.pany.domain.Product</ehcache:value-type>
    <ehcache:capacity>200</ehcache:capacity>
    <ehcache:expiry>
      <ehcache:ttl unit="millis">2</ehcache:ttl>
    </ehcache:expiry>
    <ehcache:eviction-veto>com.pany.ehcache.MyEvictionVeto</ehcache:eviction-veto>
    <ehcache:eviction-prioritizer>FIFO</ehcache:eviction-prioritizer>
    <ehcache:integration>
      <ehcache:loader>
        <ehcache:class>com.pany.ehcache.integration.ProductCacheLoader</ehcache:class>
      </ehcache:loader>
      <ehcache:writer>
        <ehcache:class>com.pany.ehcache.integration.ProductCacheWriter</ehcache:class>
      </ehcache:writer>
    </ehcache:integration>
  </ehcache:cache-template>
</ehcache:config>

``` 


Java code to create a default cache with templates applied:


```
CachingProvider provider = Caching.getCachingProvider();

    //Create cache manager using the templated configuration
    CacheManager manager = provider.getCacheManager(getClass().getResource("/ehcache-107-config-overriding.xml")
        .toURI(), provider.getDefaultClassLoader());

    MutableConfiguration<Long, String> conf = new MutableConfiguration<Long, String>();
    conf.setTypes(Long.class, String.class);

    javax.cache.Cache<Long, String> cache = manager.createCache("default-cache", conf);

    assertThat("Creating cache with default template<Long, String> should not return null",
        cache, is(notNullValue()));

```
Values in the `Eh107CompleteConfiguration`

Configuration Key | Actual Value | Source
-----|-----|-----
Key |  Long | Template
Value | String | Template
Capacity | 2 | Template
Expiry Policy | Eternal | Conf
Loader | Null | Conf
Writer | Null | Conf

Code to create product cache:

```

 MutableConfiguration<Long, Product> pConf = new MutableConfiguration<Long, Product>();
    pConf.setTypes(Long.class, Product.class);

    javax.cache.Cache<Long, Product> pCache = manager.createCache("productCache", pConf);

```
Values in the `Eh107CompleteConfiguration`

Configuration Key | Actual Value | Source
-----|-----|-----
Key |  Long | Template
Value | String | Template
Capacity | 200 | Template
Expiry Policy | Eternal | Conf
Loader | Null | Conf
Writer | Null | Conf

Looking at two tables, some properties are picked up from the configuration whereas some are picked from the XML Template. So what should be the way ahead?

IMO, we should be overriding the values in `MutableConfiguration` with the values in the template, and those values should be persisted in the configuration returned to the user, [along with properties mentioned in the comment.](https://github.com/ehcache/ehcache3/issues/216#issuecomment-69153676)
 
Also just to add another _odd_ behavior:

```
MutableConfiguration<String, String> conf = new MutableConfiguration<Long, String>();
    conf.setTypes(String.class, String.class);
    javax.cache.Cache<String, String> cache = manager.createCache("default1", conf);

```

The creation of `default1` cache fails as the key types differs, we should address this issue. If no key/value types are defined in xml template, only caches of type Object, Object is allowed. This means we cannot override the types in cases of templates which  don't have any types defined.


We should either relax the current restriction in the `XMLConfiguration` to allow sub-classes of the key value types in the template or drop them.

**Comment by ljacomet** [comment] 2015-02-05 10:39
After a discussion with @sreekanth-r, there is a proposition formed and to be discussed in the public dev meeting of February 5th. Hopefully agreement is reached and this task can then be implemented and closed.

**Comment by ljacomet** [comment] 2015-02-05 20:18
During the Ehcache public dev meeting, we confirmed what was discussed with @sreekanth-r.

The following code explains what we want to achieve:


``` java
  @Test
  public void testCompleteConfigEhcacheStyle() {
    Eh107MutableConfiguration<Long, String> configuration = new Eh107MutableConfiguration<Long, String>(Long.class, String.class);
    // This will overwrite expiry
    configuration.setExpiry(CreatedExpiryPolicy.factoryOf(new Duration(TimeUnit.SECONDS, 60)));

    // All unset properties will use the template and if not defined a default - matching MutableConfiguration defaults
    
    cacheManager.createCache("otherCache", configuration);
  }

  @Test
  public void testMutableConfigIntegration() {
    MutableConfiguration<Long, String> configuration = new MutableConfiguration<Long, String>();
    configuration.setTypes(Long.class, String.class);

    assertThat(configuration.getExpiryPolicyFactory(), is(EternalExpiryPolicy.factoryOf()));
    cacheManager.createCache("thirdCache", configuration);
    // You get a cache with eternal expiry, even if defined differently in the template
    // Same goes for all the other properties
    configuration.getCacheEntryListenerConfigurations();
    configuration.isManagementEnabled();
    configuration.isStatisticsEnabled();

    // Only special part is with read/write through and Loader/Writer
    if (configuration.isReadThrough() == false) {
      // ignore LoaderWriter from template - Most likely needs to change comapred to what's implemented now
    }
    if (configuration.isReadThrough() && configuration.getCacheLoaderFactory() == null) {
      // Use template provided one if any, error otherwise
    }
  }
```

This means this task has two sides:
* Align the behaviour when getting a CompleteConfiguration which is not an Ehcache one.
* Create the `Eh107MutableConfiguration`
  * Find it a proper name
  * Make it smart with regards to value source: user set or default

**Comment by ljacomet** [comment] 2015-02-06 11:19
One addition that was discussed in the meeting: any template value overridden by a value in a JSR-107 `CompleteConfiguration` should be logged at  `WARN` level.

**Comment by ljacomet** [comment] 2015-02-26 16:43
Looks like that latest PR I merged slipped in a few extra changes in the last iteration.
I have fixed the missing copyright header. However, please try to keep the PR on topic in the future.
And what's there currently does not match the end expectation - I do no think we should extend `MutableConfiguration` for any reason.

**Comment by ljacomet** [comment] 2015-02-26 16:57
Ok I lied, not fixing the static analysis stuff. Please propose a new PR getting rid of `Eh107MutableConfiguration` for the moment and adding the copyright header on `Eh107JSRTemplateOverridingTest`.
There are findbugs issues after the checkstyle ones ...

**Comment by ljacomet** [comment] 2015-05-12 11:33
Copying results from mailing list discussion:
> We need to view the topic with two use cases in mind: My application code has no direct Ehcache dependency (existing or choice) and My application code has direct Ehcache dependency.
>
> In the latter, the Eh107ConfigurationWrapper proposition remains valid as a way to get the full benefits of Ehcache 3 features but using CacheManager and Cache APIs from 107. And in this context the Eh107SimpleConfiguration makes no sense at all.
>
> But when I do not want a direct Ehcache 3 dependency, I can use XML configuration and define complete caches in it, that I will simply "get" from the CacheManager.
> However, I may have existing code that use a MutableConfiguration. So here the proposition would be to design the system as: 
> I start with 107 and I potentially override configuration through Ehcache XML templates.
>
> And so in this context, if I am happy with 107 defaults, my template would only cover the rest of the configuration. But also, if whatever code exists in an application - whether or not I can modify it - I have the option to override what's in the MutableConfiguration by defining something else in my XML template.

[Complete discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ehcache-dev/Oaf7qTsojfM/vDFBhW2eKt4J)

**Closed** 2015-05-29 16:01 UTC
Labels: jsr107
