### ISSUE TITLE
Putting large values in cache throws after a while with storage engine failure

### ISSUE THREAD

**Issue by skraemer0** [ehcache/ehcache3#2851] opened 2020-10-08 14:10 UTC
Hi, we are experiencing the same issue as in [#1772](https://github.com/ehcache/ehcache3/issues/1772) with version 3.4.0 clustered. After putting large values into the cache (~13 MB) and fetching them again, the following error is thrown:

```
[WorkerThread(request_processor_stage, 6, 6)] ERROR org.ehcache.clustered.server.store.ClusterTierActiveEntity - Unexpected exception raised during operation: GET_AND_APPEND
org.terracotta.offheapstore.exceptions.OversizeMappingException: Storage Engine and Eviction Failed - Empty Map
Storage Engine : org.ehcache.clustered.server.offheap.OffHeapChainStorageEngine@2988391d
	at org.terracotta.offheapstore.AbstractOffHeapClockCache.storageEngineFailure(AbstractOffHeapClockCache.java:84) ~[offheap-store-2.3.2.jar:na]
	at org.terracotta.offheapstore.OffHeapHashMap.writeEntry(OffHeapHashMap.java:689) ~[offheap-store-2.3.2.jar:na]
	at org.terracotta.offheapstore.OffHeapHashMap.put(OffHeapHashMap.java:471) ~[offheap-store-2.3.2.jar:na]
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.put(AbstractLockedOffHeapHashMap.java:145) ~[offheap-store-2.3.2.jar:na]
	at org.terracotta.offheapstore.OffHeapHashMap.put(OffHeapHashMap.java:461) ~[offheap-store-2.3.2.jar:na]
	at org.terracotta.offheapstore.AbstractLockedOffHeapHashMap.put(AbstractLockedOffHeapHashMap.java:134) ~[offheap-store-2.3.2.jar:na]
	at org.ehcache.clustered.server.offheap.OffHeapChainMap.getAndAppend(OffHeapChainMap.java:111) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.clustered.server.offheap.OffHeapServerStore.getAndAppend(OffHeapServerStore.java:139) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.clustered.server.ServerStoreImpl.getAndAppend(ServerStoreImpl.java:74) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.clustered.server.store.ClusterTierActiveEntity.invokeServerStoreOperation(ClusterTierActiveEntity.java:392) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.clustered.server.store.ClusterTierActiveEntity.invokeActiveInternal(ClusterTierActiveEntity.java:257) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.terracotta.client.message.tracker.OOOMessageHandlerImpl.invoke(OOOMessageHandlerImpl.java:47) ~[client-message-tracker-5.3.1.jar:na]
	at org.ehcache.clustered.server.store.ClusterTierActiveEntity.invokeActive(ClusterTierActiveEntity.java:247) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at org.ehcache.clustered.server.store.ClusterTierActiveEntity.invokeActive(ClusterTierActiveEntity.java:105) ~[ehcache-server-3.4.0.jar:3.4.0 45a1f99e0d65f13bdd379e60a5ca9a7b6d3a90bc]
	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:760) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:510) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$2(ManagedEntityImpl.java:335) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:1121) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:171) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:162) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27) ~[dso-l2-5.3.2.jar:na]
	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23) ~[dso-l2-5.3.2.jar:na]
	at com.tc.async.impl.AbstractStageQueueImpl$HandledContext.runWithHandler(AbstractStageQueueImpl.java:207) ~[common-5.3.2.jar:na]
	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197) ~[common-5.3.2.jar:na]
```

Our client config looks like:
```xml
    <tc:cluster>
      <tc:connection url="terracotta://host:9510/cachemanager"/>
      <tc:read-timeout unit="seconds">3</tc:read-timeout>
      <tc:server-side-config auto-create="true">
        <tc:shared-pool name="shared-pool" from="primary-server-resource" unit="MB">400</tc:shared-pool>
      </tc:server-side-config>
    </tc:cluster>
```

I can reproduce this error with a script that puts large values (~13 MB) into a cache and fetches them afterwards. It is also reproducible with version 3.8.1. Is this a configuration issue (like cache too small) or is it a bug?

**Comment by chrisdennis** [comment] 2020-10-08 14:16
Could you share the rest of your configuration (the caches themselves)?

**Comment by skraemer0** [comment] 2020-10-08 14:18
```xml
<ehcache:config
    xmlns:ehcache="http://www.ehcache.org/v3"
    xmlns:jcache="http://www.ehcache.org/v3/jsr107"
	xmlns:tc="http://www.ehcache.org/v3/clustered" >
	<ehcache:service>
		<tc:cluster>
			<tc:connection url="terracotta://host:9510/cachemanager"/>
			<tc:read-timeout unit="seconds">3</tc:read-timeout>
			<tc:server-side-config auto-create="true">
				<tc:shared-pool name="shared-pool" from="primary-server-resource" unit="MB">400</tc:shared-pool>
			</tc:server-side-config>
		</tc:cluster>
	</ehcache:service>
	<ehcache:cache alias="ProjectAttribut">
		<ehcache:key-type>java.lang.String</ehcache:key-type>
		<ehcache:value-type>java.util.HashMap</ehcache:value-type>	
		<ehcache:resources>
			<ehcache:heap unit="entries">500</ehcache:heap>
			<tc:clustered-shared sharing="shared-pool" />
		</ehcache:resources>
		<tc:clustered-store consistency="strong"/>
	</ehcache:cache>
	<ehcache:cache alias="ProjectList">
		<ehcache:key-type>java.lang.String</ehcache:key-type>
		<ehcache:value-type>java.util.LinkedHashMap</ehcache:value-type>	
		<ehcache:resources>
			<ehcache:heap unit="entries">500</ehcache:heap>
			<tc:clustered-shared sharing="shared-pool" />
		</ehcache:resources>
		<tc:clustered-store consistency="strong"/>
	</ehcache:cache>
	<ehcache:cache alias="CodeList">
		<ehcache:key-type>java.lang.String</ehcache:key-type>
		<ehcache:value-type>java.util.ArrayList</ehcache:value-type>	
		<ehcache:resources>
			<ehcache:heap unit="entries">50</ehcache:heap>
			<tc:clustered-shared sharing="shared-pool" />
		</ehcache:resources>
		<tc:clustered-store consistency="strong"/>
	</ehcache:cache>
	<ehcache:cache alias="ProjectSetting">
		<ehcache:key-type>java.lang.String</ehcache:key-type>
		<ehcache:value-type>java.util.ArrayList</ehcache:value-type>	
		<ehcache:expiry>
			<ehcache:ttl unit="minutes">360</ehcache:ttl>
		</ehcache:expiry>
		<ehcache:resources>
			<ehcache:heap unit="entries">70</ehcache:heap>
			<tc:clustered-shared sharing="shared-pool" />
		</ehcache:resources>
		<tc:clustered-store consistency="strong"/>
	</ehcache:cache>
	<ehcache:cache alias="ExternalUsers">
		<ehcache:key-type>java.lang.String</ehcache:key-type>
		<ehcache:value-type>java.util.LinkedHashMap</ehcache:value-type>	
		<ehcache:resources>
			<ehcache:heap unit="entries">70</ehcache:heap>
			<tc:clustered-shared sharing="shared-pool" />
		</ehcache:resources>
		<tc:clustered-store consistency="strong"/>
	</ehcache:cache>
	<ehcache:cache alias="PlannedDocuments">
		<ehcache:key-type>java.lang.String</ehcache:key-type>
		<ehcache:value-type>java.util.LinkedHashMap</ehcache:value-type>	
		<ehcache:resources>
			<ehcache:heap unit="entries">70</ehcache:heap>
			<tc:clustered-shared sharing="shared-pool" />
		</ehcache:resources>
		<tc:clustered-store consistency="strong"/>
	</ehcache:cache>
</ehcache:config>
```

**Comment by chrisdennis** [comment] 2020-10-08 14:23
If you can reproduce this with only a single cache then this may be a new bug. Given that you are sharing your 400MB pool between multiple caches though I suspect that you're seeing a symptom of #2215. Currently I can't give you an ETA on a fix for this issue, but I can report it's not so much a bug as a chunk of missing implementation. Fixing it isn't going to be a trivial task. My recommendation right now would be to size your caches individually instead (`<tc:clustered-dedicated>`).

**Comment by skraemer0** [comment] 2020-10-09 11:00
Thanks for your reply. Seems like clustered-dedicated is solving our problem. At least I was not able to reproduce the error with the test.

**Comment by chrisdennis** [comment] 2020-10-09 14:59
Closing this as a duplicate of #2215

**Closed by chrisdennis** 2020-10-09 14:59 UTC
Labels: bug, clustering, duplicate
