### ISSUE TITLE
New version of platform (5.0.12.beta) breaks BasicClusteredCacheOpsReplicationMultiThreadedTest

### ISSUE THREAD

**Issue by anthonydahanne** [ehcache/ehcache3#1650] opened 2016-11-24 14:51 UTC
Supposedly because of a runnel change
Here is the stack trace : 

```
 com.tc.exception.TCRuntimeException: Uncaught exception in stage
 	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:211)
 Caused by: java.lang.RuntimeException: org.terracotta.exception.EntityUserException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:crud-cm-replication exception in user code: org.terracotta.exception.EntityUserException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:crud-cm-replication exception in user code: Runtime exception in deserializer
 	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:403)
 	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$processInvokeRequest$73(ManagedEntityImpl.java:238)
 	at com.tc.objectserver.entity.ManagedEntityImpl$$Lambda$31/409111087.run(Unknown Source)
 	at com.tc.objectserver.entity.ManagedEntityImpl$SchedulingRunnable.run(ManagedEntityImpl.java:908)
 	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.invoke(RequestProcessor.java:157)
 	at com.tc.objectserver.entity.RequestProcessor$EntityRequest.run(RequestProcessor.java:149)
 	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:27)
 	at com.tc.objectserver.entity.RequestProcessorHandler.handleEvent(RequestProcessorHandler.java:23)
 	at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
 	at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)
 Caused by: org.terracotta.exception.EntityUserException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:crud-cm-replication exception in user code: org.terracotta.exception.EntityUserException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:crud-cm-replication exception in user code: Runtime exception in deserializer
 	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:401)
 	... 9 more
 Caused by: java.lang.RuntimeException: org.terracotta.exception.EntityUserException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:crud-cm-replication exception in user code: Runtime exception in deserializer
 	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:629)
 	at com.tc.objectserver.entity.ManagedEntityImpl.invoke(ManagedEntityImpl.java:380)
 	... 9 more
 Caused by: org.terracotta.exception.EntityUserException: Entity: org.ehcache.clustered.client.internal.EhcacheClientEntity:crud-cm-replication exception in user code: Runtime exception in deserializer
 	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:292)
 	at com.tc.objectserver.entity.ManagedEntityImpl.performAction(ManagedEntityImpl.java:622)
 	... 10 more
 Caused by: org.terracotta.entity.MessageCodecException: Runtime exception in deserializer
 	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:291)
 	... 11 more
 Caused by: java.lang.IllegalArgumentException: No such field : elements
 	at org.terracotta.runnel.metadata.FieldSearcher.findField(FieldSearcher.java:40)
 	at org.terracotta.runnel.encoding.StructEncoder.structs(StructEncoder.java:222)
 	at org.ehcache.clustered.common.internal.messages.ChainCodec.encode(ChainCodec.java:55)
 	at org.ehcache.clustered.common.internal.messages.ResponseCodec$1.encode(ResponseCodec.java:118)
 	at org.terracotta.runnel.encoding.StructEncoder.struct(StructEncoder.java:130)
 	at org.ehcache.clustered.common.internal.messages.ResponseCodec.encode(ResponseCodec.java:113)
 	at org.ehcache.clustered.common.internal.messages.EhcacheCodec.encodeResponse(EhcacheCodec.java:112)
 	at org.ehcache.clustered.server.internal.messages.EhcacheServerCodec.encodeResponse(EhcacheServerCodec.java:86)
 	at org.ehcache.clustered.server.internal.messages.EhcacheServerCodec.encodeResponse(EhcacheServerCodec.java:37)
 	at com.tc.objectserver.entity.ManagedEntityImpl.lambda$performAction$78(ManagedEntityImpl.java:622)
 	at com.tc.objectserver.entity.ManagedEntityImpl$$Lambda$32/1717492671.run(Unknown Source)
 	at com.tc.objectserver.entity.ManagedEntityImpl.runWithHelper(ManagedEntityImpl.java:286)
 	... 11 more
```

You can also find the stacktrace on cloubees (search for elements) : https://ehcache.ci.cloudbees.com/job/ehcache3-pull-requests/3482/jdk=Oracle%20JDK%201.8(latest),label_exp=standard,testVM=8/testReport/junit/org.ehcache.clustered.replication/BasicClusteredCacheOpsReplicationMultiThreadedTest/testClear_consistency_EVENTUAL_/

**Comment by lorban** [comment] 2016-11-25 10:20
The runnel struct aliasing feature was causing this regression, so it's been backed out (https://github.com/Terracotta-OSS/terracotta-platform/issues/199) as no merged code requires it yet.

I'm now investigating what exactly in that new feature introduced that bug.

**Comment by lorban** [comment] 2016-11-25 11:29
Root Cause Analysis done; the problem is that while runnel isn't supposed to be thread-safe, it still has to provide some safety in multi-threaded environments.

`Encoder`s and `Decoder`s are not thread-safe and need not be, but many threads accessing a pre-initialized `Struct` to request an `Encoder` or a `Decoder` is an obvious use-case that must be supported by runnel.

The backed-out implementation of the aliasing feature was deferring `Struct` initialization until the very first time an encoder or decoder was requested, while none of the internal structures were thread-safe nor properly guarded.

https://github.com/Terracotta-OSS/terracotta-platform/issues/202 has been opened to make sure the required thread-safety characteristics en up being documented.

**Closed by lorban** 2016-11-25 11:29 UTC
