### ISSUE TITLE
EHCache-clustered 3.5.2 imports private org.ehcache.xml.model

### ISSUE THREAD

**Issue by Hibbo** [ehcache/ehcache3#2477] opened 2018-09-06 12:50 UTC
Hi,

I am trying to integrate EHCache into Adobe Experience Manager (Sling application).
My module is importing dependencies 
```
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
        </dependency>
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache-clustered</artifactId>
        </dependency>
```
Version 3.5.2.

After OSGI bundle deployment, ehcache-clustered bundle is not starting due to missing dependency
`org.ehcache.xml.model -- Cannot be resolved`
This package is not exported by ehcache library (its private).

ehcache-clustered should not have a private dependency.

**Comment by henri-tremblay** [comment] 2018-09-06 14:04
You are right. Clustered used `org.ehcache.xml.model.TimeType` which is not exported by ehcache. 

Thanks for reporting.

**Comment by chrisdennis** [comment] 2018-09-06 14:06
@henri-tremblay I'm already looking at some of the XML parsing for other reasons... I'll have a dig on this if thats okay.

**Comment by henri-tremblay** [comment] 2018-09-06 14:17
Sure. All yours :-)

**Comment by chrisdennis** [comment] 2018-09-13 17:31
The problem is a lot deeper than that... this issue is just the tip of a great big OSGi iceberg.  If you want things to work right now you'll likely need to create your own bundle that merges the two jars. I have a fix the bigger issue but it's pretty involved and will have to wait for a release (obviously).

**Comment by chrisdennis** [comment] 2018-09-17 20:58
@Hibbo - have a look at PR #2488 which shows my current plan for how to fix this.  In particular the new `ClusteredOsgiTest` covers what you are trying to do here.  This needs review, and some discussion about what conditions should trigger this kind of service lookup, so I can't give you an ETA... but it at least gives you an idea what I'm planning.

**Comment by Hibbo** [comment] 2018-11-14 14:37
@chrisdennis thanks a lot! Is there any update on when it will be stable to be included in release?

**Comment by chrisdennis** [comment] 2018-11-14 15:05
The PR needs some work to catch up with the latest changes merged in to master... unfortunately I'm too busy with other things to do that right now. To be honest I'll only be able to give you a good timeline once this is merged. Sorry!

**Comment by chrisdennis** [comment] 2019-02-06 17:15
#2488 is now merged... and there should be an Ehcache release happening in the next month or so with this and a bunch of other fixes.

**Closed** 2019-02-06 17:16 UTC
Labels: bug
