### ISSUE TITLE
TieredStore doesn't populate the caching tier on getAll(...)

### ISSUE THREAD

**Issue by arpitmalhotra** [ehcache/ehcache3#3097] opened 2022-12-14 05:58 UTC
I have the following ehcache configuration. But it seems only the offheap component reports metrics(hits, size etc) but onheap is never allocated in this config. 

```java
CacheManager cacheManager = CacheManagerBuilder.newCacheManagerBuilder()
              .using(statisticsService)
              .withCache("cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(String.class, String.class, ResourcePoolsBuilder.newResourcePoolsBuilder()
                                          .heap(1, MemoryUnit.GB).offheap(3, MemoryUnit.GB).build())
                                          .withExpiry(ExpiryPolicyBuilder.timeToLiveExpiration(Duration.ofMinutes(10)))
                                          .withService(WriteBehindConfigurationBuilder.newUnBatchedWriteBehindConfiguration()
                                                              .queueSize(10)
                                                              .concurrencyLevel(10).build()))
                                          .build();
cacheManager.init();
```

**Comment by chrisdennis** [comment] 2022-12-14 19:38
Without a lot more information it's hard to know what is going on here. It seems much more likely that this is a usage issue, and not a bug. I would suggest that unless you have a reproducible test case (or a enough information for someone to build one) then this isn't a bug and should be directed to https://groups.google.com/g/ehcache-users

**Comment by arpitmalhotra** [comment] 2022-12-14 20:45
can you advise what further information you need ? with the above configuration i am not seeing the on heap being used. this is evident in the tier statistics from on heap.

**Comment by chrisdennis** [comment] 2022-12-14 21:09
I think you might be expecting the heap to be getting populated on put... as the current cache behavior that is not true:

```java
@Test
public void testTierUsage() {
  StatisticsService statisticsService = new DefaultStatisticsService();

  try (CacheManager cacheManager = newCacheManagerBuilder().using(statisticsService)
    .withCache("cache", newCacheConfigurationBuilder(String.class, String.class, newResourcePoolsBuilder()
      .heap(1, MemoryUnit.MB)
      .offheap(2, MemoryUnit.MB))
      .withExpiry(timeToLiveExpiration(ofMinutes(10)))
      .withService(newUnBatchedWriteBehindConfiguration().queueSize(10).concurrencyLevel(10))).build(true)) {

    Cache<String, String> cache = cacheManager.getCache("cache", String.class, String.class);

    CacheStatistics cacheStatistics = statisticsService.getCacheStatistics("cache");

    System.out.println(cacheStatistics.getTierStatistics().keySet());
    TierStatistics heap = cacheStatistics.getTierStatistics().get("OnHeap");
    TierStatistics offheap = cacheStatistics.getTierStatistics().get("OffHeap");

    cache.put("foo", "bar");
    assertThat(heap.getMappings(), is(0L));
    assertThat(offheap.getMappings(), is(1L));

    cache.get("foo");
    assertThat(heap.getMappings(), is(1L));
    assertThat(offheap.getMappings(), is(1L));
  }
}
```

If you're seeing something else then feel free to modify this test to expose the behavior you think is buggy.

**Comment by arpitmalhotra** [comment] 2022-12-14 21:30
This is the bug.  i am using cache.getAll instead of cache.get. See modified code

@Test
public void testTierUsage() {
  StatisticsService statisticsService = new DefaultStatisticsService();

  try (CacheManager cacheManager = newCacheManagerBuilder().using(statisticsService)
    .withCache("cache", newCacheConfigurationBuilder(String.class, String.class, newResourcePoolsBuilder()
      .heap(1, MemoryUnit.MB)
      .offheap(2, MemoryUnit.MB))
      .withExpiry(timeToLiveExpiration(ofMinutes(10)))
      .withService(newUnBatchedWriteBehindConfiguration().queueSize(10).concurrencyLevel(10))).build(true)) {

    Cache<String, String> cache = cacheManager.getCache("cache", String.class, String.class);

    CacheStatistics cacheStatistics = statisticsService.getCacheStatistics("cache");

    System.out.println(cacheStatistics.getTierStatistics().keySet());
    TierStatistics heap = cacheStatistics.getTierStatistics().get("OnHeap");
    TierStatistics offheap = cacheStatistics.getTierStatistics().get("OffHeap");

    cache.put("foo", "bar");
    assertThat(heap.getMappings(), is(0L));
    assertThat(offheap.getMappings(), is(1L));

    cache.getAll(new HashSet(Arrays.asList("foo")));
    assertThat(heap.getMappings(), is(1L));
    assertThat(offheap.getMappings(), is(1L));
  }
}

**Comment by arpitmalhotra** [comment] 2022-12-15 03:09
Can we reopen this as bug @chrisdennis

**Comment by chrisdennis** [comment] 2022-12-16 16:23
The above back-and-forth confirmed that this is a long-standing bug in the TieredStore.

**Comment by nnares** [comment] 2023-01-02 11:05
Analyzed this issue, Here is my finding :
We are getting this CacheStatistics difference, because of current implementation for both of the method
`cache.get() > TieredStore#bulkComputeIfAbsent()` : it fetches the cache entry from authoritativeTier and load it to heapTier for subsequent fetch, and pass it to client
`cache.getAll() > TieredStore#bulkComputeIfAbsent()` : it simply fetches the cache entry from authoritativeTier and pass it to client
We need a discussion around this.

**Comment by nnares** [comment] 2023-08-18 13:46
Fixed in https://github.com/ehcache/ehcache3/pull/3130. Clsoing the issue now

**Closed by nnares** 2023-08-18 13:46 UTC
Labels: bug, in progress
