### ISSUE TITLE
Ehcache fails to reconnect to server after a while

### ISSUE THREAD

**Issue by henri-tremblay** [ehcache/ehcache3#2300] opened 2018-02-19 20:29 UTC
I'm cutting and re-establishing the network connection between a client and a server. It works for a little while but fails at some point. The client never reconnects.

Here is the test case. It is using toxiproxy server launched locally with default parameters.

In `build.gradle`:

```
testCompile 'eu.rekawek.toxiproxy:toxiproxy-java:2.1.2'
```

```java
import eu.rekawek.toxiproxy.Proxy;
import eu.rekawek.toxiproxy.ToxiproxyClient;
import org.ehcache.Cache;
import org.ehcache.PersistentCacheManager;
import org.ehcache.clustered.client.config.builders.ClusteredResourcePoolBuilder;
import org.ehcache.clustered.client.config.builders.ClusteredStoreConfigurationBuilder;
import org.ehcache.clustered.client.config.builders.ClusteringServiceConfigurationBuilder;
import org.ehcache.clustered.client.config.builders.TimeoutsBuilder;
import org.ehcache.clustered.common.Consistency;
import org.ehcache.config.builders.CacheConfigurationBuilder;
import org.ehcache.config.builders.CacheManagerBuilder;
import org.ehcache.config.builders.ResourcePoolsBuilder;
import org.ehcache.config.units.MemoryUnit;
import org.junit.After;
import org.junit.Before;
import org.junit.ClassRule;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestName;
import org.terracotta.testing.rules.Cluster;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.time.Duration;
import java.util.concurrent.Phaser;
import java.util.concurrent.atomic.AtomicReference;

import static eu.rekawek.toxiproxy.model.ToxicDirection.DOWNSTREAM;
import static org.assertj.core.api.Assertions.assertThat;
import static org.terracotta.testing.rules.BasicExternalClusterBuilder.newCluster;

public class NetworkFailureTest extends ClusteredTests {

  private static final String RESOURCE_CONFIG =
    "<config xmlns:ohr='http://www.terracotta.org/config/offheap-resource'>"
    + "<ohr:offheap-resources>"
    + "<ohr:resource name=\"primary-server-resource\" unit=\"MB\">512</ohr:resource>"
    + "</ohr:offheap-resources>"
    + "</config>"
    + "<service xmlns:lease='http://www.terracotta.org/service/lease'>"
    + "<lease:connection-leasing>"
    + "<lease:lease-length unit='seconds'>5</lease:lease-length>"
    + "</lease:connection-leasing>"
    + "</service>\n";

  private PersistentCacheManager cacheManager;

  private ToxiproxyClient client;
  private Proxy activeProxy;

  @ClassRule
  public static Cluster CLUSTER = newCluster(1)
    .in(new File("build/cluster"))
    .withServiceFragment(RESOURCE_CONFIG)
    .build();

   @Rule
   public TestName name = new TestName();

  @Before
  public void startServers() throws Exception {
    CLUSTER.getClusterControl().startAllServers();
    CLUSTER.getClusterControl().waitForActive();

    URI clusterUri = CLUSTER.getConnectionURI();

    client = new ToxiproxyClient();
    try {
      activeProxy = client.getProxy("NetworkFailureTest.proxy");
      activeProxy.delete();
    } catch (IOException e) {
      // It means the proxy isn't there. Just ignore
    }
    activeProxy = client.createProxy("NetworkFailureTest.proxy", "0.0.0.0:21212", "localhost" + ":" + clusterUri.getPort());

    URI proxyUri = URI.create("terracotta://localhost:21212");

    CacheManagerBuilder<PersistentCacheManager> builder = CacheManagerBuilder.newCacheManagerBuilder()
      .with(ClusteringServiceConfigurationBuilder.cluster(proxyUri)
        .timeouts(TimeoutsBuilder.timeouts().write(Duration.ofSeconds(20)))
        .autoCreate())
      .withCache("cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Integer.class, String.class,
        ResourcePoolsBuilder.newResourcePoolsBuilder()
          .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 32, MemoryUnit.MB)))
        .add(ClusteredStoreConfigurationBuilder.withConsistency(Consistency.STRONG)));

    cacheManager =  builder.build(true);
  }

  @After
  public void tearDown() throws Exception {
    System.out.println("*************************************************** TearDown ***************************************************");
    client.reset();

    if(cacheManager != null) {
      cacheManager.close();
      cacheManager.destroy();
    }
    activeProxy.delete();

    CLUSTER.getClusterControl().terminateAllServers();
  }

  @Test
  public void proxy() throws Exception {

    Cache<Integer, String> cache = cacheManager.getCache("cache", Integer.class, String.class);

    for (int i = 0; i < 100; i++) {
      System.out.println("***************************************** Loop: " + i);
      upAndDown(cache);
    }
  }

  private void upAndDown(Cache<Integer, String> cache) throws InterruptedException {
    Phaser phaser = new Phaser(2);

    AtomicReference<Throwable> exception = new AtomicReference<>();

    Thread thread = new Thread(() -> {
      try {
        // Everything is alright phase
        phaser.arriveAndAwaitAdvance();
        Thread.sleep(5_000);

        // Loosing connection phase
        phaser.arriveAndAwaitAdvance();
        activeProxy.toxics().timeout("failing", DOWNSTREAM, 5_000);
        Thread.sleep(10_000);

        // Getting back connection phase
        phaser.arriveAndAwaitAdvance();
        activeProxy.toxics().get("failing").remove();
      } catch(Throwable e) {
        exception.set(e);
      } finally {
        phaser.arriveAndDeregister();
      }
    });

    thread.start();

    cache.put(1, "a");

    // Everything is alright phase
    System.out.println("************************** Alright");
    phaser.arriveAndDeregister();
    while(phaser.getPhase() == 0) {
      assertThat(cache.get(1)).isEqualTo("a");
      Thread.sleep(1_000);
    }

    // Loosing connection phase
    System.out.println("************************** Loosing");
    while(cache.get(1) != null) {
      Thread.sleep(1_000);
    }

    // Getting back connection phase
    System.out.println("************************** Back to our feet");
    while(cache.get(1) == null) {
      System.out.println("Trying to get connection back");
      cache.put(1, "a");
      Thread.sleep(1_000);
    }

    while(!phaser.isTerminated());

    assertThat(exception.get()).isNull();

    System.out.println("************************** All done");
  }
}
```

The full code is here: https://github.com/henri-tremblay/ehcache3/tree/networkingtest

**Comment by AbfrmBlr** [comment] 2018-02-21 18:36
The test is failing because, voltron throws a ConnectionException instead of ConnectionClosedException or ConnectionShutdownException.
Below is the stack trace :

org.terracotta.connection.ConnectionException: java.lang.RuntimeException: java.lang.IllegalStateException: com.tc.util.concurrent.TCExceptionResultException: java.io.IOException: connection closed
	at com.terracotta.connection.api.AbstractConnectionService.connect(AbstractConnectionService.java:82)
	at org.terracotta.connection.ConnectionFactory.connect(ConnectionFactory.java:46)
	at org.terracotta.lease.connection.LeasedConnectionServiceImpl.connect(LeasedConnectionServiceImpl.java:42)
	at org.terracotta.lease.connection.LeasedConnectionFactory.connect(LeasedConnectionFactory.java:46)
	at org.ehcache.clustered.client.internal.service.ConnectionState.initClusterConnection(ConnectionState.java:119)
	at org.ehcache.clustered.client.internal.service.ConnectionState.handleConnectionClosedException(ConnectionState.java:268)
	at org.ehcache.clustered.client.internal.service.ConnectionState.createClusterTierClientEntity(ConnectionState.java:104)
	at org.ehcache.clustered.client.internal.service.DefaultClusteringService.getServerStoreProxy(DefaultClusteringService.java:259)
	at org.ehcache.clustered.client.internal.store.ClusteredStore$Provider.initStore(ClusteredStore.java:660)
	at org.ehcache.clustered.client.internal.store.ClusteredStore$Provider.lambda$null$0(ClusteredStore.java:706)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: com.tc.util.concurrent.TCExceptionResultException: java.io.IOException: connection closed
	at com.tc.object.DistributedObjectClient.waitForConnection(DistributedObjectClient.java:396)
	at com.tc.object.DistributedObjectClientFactory.create(DistributedObjectClientFactory.java:97)
	at com.terracotta.connection.TerracottaInternalClientImpl.init(TerracottaInternalClientImpl.java:60)
	at com.terracotta.connection.api.AbstractConnectionService.connect(AbstractConnectionService.java:80)
	... 13 more
Caused by: java.lang.IllegalStateException: com.tc.util.concurrent.TCExceptionResultException: java.io.IOException: connection closed
	at com.tc.object.DistributedObjectClient.openChannel(DistributedObjectClient.java:430)
	at com.tc.object.DistributedObjectClient.access$400(DistributedObjectClient.java:125)
	at com.tc.object.DistributedObjectClient$5.run(DistributedObjectClient.java:355)
	... 1 more
Caused by: com.tc.net.protocol.transport.TransportHandshakeException: com.tc.util.concurrent.TCExceptionResultException: java.io.IOException: connection closed
	at com.tc.net.protocol.transport.ClientMessageTransport.handShake(ClientMessageTransport.java:326)
	at com.tc.net.protocol.transport.ClientMessageTransport.handshakeConnection(ClientMessageTransport.java:423)
	at com.tc.net.protocol.transport.ClientMessageTransport.openConnection(ClientMessageTransport.java:377)
	at com.tc.net.protocol.transport.ClientMessageTransport.open(ClientMessageTransport.java:112)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher.connectTryAllOnce(ClientConnectionEstablisher.java:145)
	at com.tc.net.protocol.transport.ClientConnectionEstablisher.open(ClientConnectionEstablisher.java:130)
	at com.tc.net.protocol.ClientNetworkStackHarness$1.openMessageTransport(ClientNetworkStackHarness.java:98)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.open(ClientMessageChannelImpl.java:94)
	at com.tc.net.protocol.tcm.ClientMessageChannelImpl.open(ClientMessageChannelImpl.java:80)
	at com.tc.object.DistributedObjectClient.openChannel(DistributedObjectClient.java:411)
	... 3 more
Caused by: com.tc.util.concurrent.TCExceptionResultException: java.io.IOException: connection closed
	at com.tc.util.concurrent.TCFuture.get(TCFuture.java:118)
	at com.tc.util.concurrent.TCFuture.get(TCFuture.java:80)
	at com.tc.net.protocol.transport.ClientMessageTransport.handShake(ClientMessageTransport.java:321)
	... 12 more
Caused by: java.io.IOException: connection closed
	at com.tc.net.protocol.transport.ClientMessageTransport.closeEvent(ClientMessageTransport.java:228)
	at com.tc.net.core.event.TCConnectionEventCaller.fireEvent(TCConnectionEventCaller.java:94)
	at com.tc.net.core.event.TCConnectionEventCaller.fireCloseEvent(TCConnectionEventCaller.java:72)
	at com.tc.net.core.TCConnectionImpl$2.run(TCConnectionImpl.java:622)
	at com.tc.net.core.CoreNIOServices$CommThread.cleanupChannel(CoreNIOServices.java:588)
	at com.tc.net.core.CoreNIOServices$CommThread$3.run(CoreNIOServices.java:518)
	at com.tc.net.core.CoreNIOServices$CommThread.selectLoop(CoreNIOServices.java:657)
	at com.tc.net.core.CoreNIOServices$CommThread.run(CoreNIOServices.java:386)

**Comment by AbfrmBlr** [comment] 2018-02-21 18:37
Infact since we are trying to create new connection again,  we should not get a connection closed problem

**Comment by AbfrmBlr** [comment] 2018-02-21 18:51
I added `LOGGER.error("init  falied ", ex);` in `ConnectionState.initClusterConnection` to get the whole stacktrace.

**Comment by henri-tremblay** [comment] 2018-02-21 19:04
A `LOGGER.error("init failed", ex);` you mean? :-)

**Comment by henri-tremblay** [comment] 2018-02-21 20:12
I tried to replace toxiproxy with netcrusher. It's not totally equivalent because with toxiproxy I was only cutting the downstream connection. Not I'm cutting it completely. However, with netcrusher, it works. It reconnects flawlessly every time. 

The question is now: "If it toxiproxy that goes wrong and fails to recreate the connection correctly?"

Here is the code I used.

```
testCompile 'com.github.netcrusherorg:netcrusher-core:0.10'
```

```java
public class NetworkFailureTest extends ClusteredTests {

  private static final String RESOURCE_CONFIG =
    "<config xmlns:ohr='http://www.terracotta.org/config/offheap-resource'>"
    + "<ohr:offheap-resources>"
    + "<ohr:resource name=\"primary-server-resource\" unit=\"MB\">512</ohr:resource>"
    + "</ohr:offheap-resources>"
    + "</config>"
    + "<service xmlns:lease='http://www.terracotta.org/service/lease'>"
    + "<lease:connection-leasing>"
    + "<lease:lease-length unit='seconds'>5</lease:lease-length>"
    + "</lease:connection-leasing>"
    + "</service>\n";

  private PersistentCacheManager cacheManager;

  private NioReactor reactor;
  private TcpCrusher crusher;

  @ClassRule
  public static Cluster CLUSTER = newCluster(1)
    .in(new File("build/cluster"))
    .withServiceFragment(RESOURCE_CONFIG)
    .build();

   @Rule
   public TestName name = new TestName();

  @Before
  public void startServers() throws Exception {
    CLUSTER.getClusterControl().startAllServers();
    CLUSTER.getClusterControl().waitForActive();

    URI clusterUri = CLUSTER.getConnectionURI();

    reactor = new NioReactor();

    crusher = TcpCrusherBuilder.builder()
      .withReactor(reactor)
      .withBindAddress("localhost", 10080)
      .withConnectAddress("localhost", clusterUri.getPort())
      .buildAndOpen();

    URI proxyUri = URI.create("terracotta://localhost:10080");

    CacheManagerBuilder<PersistentCacheManager> builder = CacheManagerBuilder.newCacheManagerBuilder()
      .with(ClusteringServiceConfigurationBuilder.cluster(proxyUri)
        .timeouts(TimeoutsBuilder.timeouts().write(Duration.ofSeconds(20)))
        .autoCreate())
      .withCache("cache", CacheConfigurationBuilder.newCacheConfigurationBuilder(Integer.class, String.class,
        ResourcePoolsBuilder.newResourcePoolsBuilder()
          .with(ClusteredResourcePoolBuilder.clusteredDedicated("primary-server-resource", 32, MemoryUnit.MB)))
        .add(ClusteredStoreConfigurationBuilder.withConsistency(Consistency.STRONG)));

    cacheManager =  builder.build(true);
  }

  @After
  public void tearDown() throws Exception {
    System.out.println("*************************************************** TearDown ***************************************************");

    if(cacheManager != null) {
      cacheManager.close();
      cacheManager.destroy();
    }

    crusher.close();
    reactor.close();

    CLUSTER.getClusterControl().terminateAllServers();
  }

  @Test
  public void proxy() throws Exception {

    Cache<Integer, String> cache = cacheManager.getCache("cache", Integer.class, String.class);

    for (int i = 0; i < 100; i++) {
      System.out.println("***************************************** Loop: " + i);
      upAndDown(cache);
    }
  }

  private void upAndDown(Cache<Integer, String> cache) throws InterruptedException {
    Phaser phaser = new Phaser(2);

    AtomicReference<Throwable> exception = new AtomicReference<>();

    Thread thread = new Thread(() -> {
      try {
        // Everything is alright phase
        phaser.arriveAndAwaitAdvance();
        Thread.sleep(5_000);

        // Loosing connection phase
        phaser.arriveAndAwaitAdvance();
        crusher.close();
        Thread.sleep(10_000);

        // Getting back connection phase
        phaser.arriveAndAwaitAdvance();
        crusher.open();
      } catch(Throwable e) {
        exception.set(e);
      } finally {
        phaser.arriveAndDeregister();
      }
    });

    thread.start();

    cache.put(1, "a");

    // Everything is alright phase
    System.out.println("************************** Alright");
    phaser.arriveAndDeregister();
    while(phaser.getPhase() == 0) {
      assertThat(cache.get(1)).isEqualTo("a");
      Thread.sleep(1_000);
    }

    // Loosing connection phase
    System.out.println("************************** Loosing");
    while(cache.get(1) != null) {
      Thread.sleep(1_000);
    }

    // Getting back connection phase
    System.out.println("************************** Back to our feet");
    while(cache.get(1) == null) {
      System.out.println("Trying to get connection back");
      cache.put(1, "a");
      Thread.sleep(1_000);
    }

    while(!phaser.isTerminated());

    assertThat(exception.get()).isNull();

    System.out.println("************************** All done");
  }
}
```

**Comment by AbfrmBlr** [comment] 2018-02-22 13:33
Will investigate how change of proxy affects the behavior

**Comment by AbfrmBlr** [comment] 2018-02-27 13:06
Right the test uses `timeout` toxic which stops the traffic for the given time and then closes the connection, which voltron layers have trouble in figuring out as proper connnection closed and thus reconnect never happens. 
But if we use `latency`toxic, which just adds delay , then lease expiry kicks in & kills the connection, which obviously leads to proper reconnection.

So the test with toxi-proxy also works when we use `latency` toxic, but does not work with  `timeout` since the later case its the proxy which kills the connection.

**Comment by AbfrmBlr** [comment] 2018-02-27 13:22
Net crusher is not inducing delays, it just closes the connection. In that case our comm stack very observes it as a closed event, resulting in a proper reconnection all the time

**Comment by henri-tremblay** [comment] 2018-02-27 14:46
Thanks for the analysis. For me it means the current Ehcache reconnect works perfectly. However, it means we might have something to look at in Terracotta platform since a timeout toxic should pass as well. No?

**Comment by AbfrmBlr** [comment] 2018-02-27 15:06
Yes it should work, will do some more digging and then probably file a bug in core

**Comment by myronkscott** [comment] 2018-02-27 15:57
There is L1->L2 heartbeating at the platform level that will close the connection but it will not do so if the client can open a new socket connection to the server.  In that case it will assume the server is in long GC and keep the connection open.  Do you see any client-side logging related to HealthChecker?

On Feb 27, 2018, at 7:06 AM, Abhilash <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes it should work, will do some more digging and then probably file a bug in core

**Comment by AbfrmBlr** [comment] 2018-02-28 12:43
I can see following relevant logs, Though I have attached a file which has complete logs:
2018-02-28 17:50:07.349 [Ehcache [_default_]-0] INFO com.tc.net.protocol.transport.ConnectionHealthCheckerImpl: TC Client - HealthChecker Started
2018-02-28 17:50:12.449 [Connection Maker - 74ee8be954434309b31d55a15c26aa91] ERROR com.tc.object.DistributedObjectClient - Client was able to establish connection with server but handshake with server failed.
2018-02-28 17:50:12.450 [Ehcache [_default_]-0] INFO com.tc.object.DistributedObjectClient - closing down Terracotta Connection hook=false force=false channel=ChannelID=[-1] client=ClientID[-1]
2018-02-28 17:50:12.451 [HealthChecker] INFO com.tc.net.protocol.transport.ConnectionHealthCheckerImpl: TC Client - HealthChecker SHUTDOWN
2018-02-28 17:50:12.453 [Ehcache [_default_]-0] ERROR org.ehcache.clustered.client.internal.service.ConnectionState - Creation connection failed due to {}
[disconnect.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54ace8660bd95b0200fb3b4a/125516c66e82c728ace21e0d46ec9d89208d8da78aeaab01e81fe086264c22703d46f96925d6bb70bd1029590a0d1bfa485f0d45aaf08c7aa6b13a23984019af80330b2b9b645bf9fa9015ad00bd2a8a4a84bfb4884dc7ed3522e58e9d02.txt)

**Comment by AbfrmBlr** [comment] 2018-02-28 12:48
If we have some poiinters, I can get logs with debug or trace(if it helps)

**Comment by myronkscott** [comment] 2018-02-28 13:28
The connection is not closed because it is never properly established.  It looks like there is a socket connect but handshake fails so ConnectionException is being thrown.  You can't close a connection that has never been established.  Is there a different expectation?

**Closed** 2018-10-03 13:01 UTC
Labels: in progress
